apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
    <head>
      <title>My Resume</title>
    </head>
    <body>
      <h1>Welcome to My Resume</h1>
      <p>This is my resume page.</p>
    </body>
    </html>
