apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-resume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-resume
  template:
    metadata:
      labels:
        app: my-resume
    spec:
      containers:
        - name: my-resume
          image: fortiz303/my-resume:1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: html-configmap
