apiVersion: v1
kind: Service
metadata:
  name: my-resume
  labels:
    environment: production 
spec:
  type: NodePort
  selector:
    app: my-resume
  ports:
    - name: http
      port: 32480
      targetPort: 80
